---
- name: Create directory
  become: yes
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Copy compressed backend folder 
  become: yes
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend
    owner: ubuntu

- name: Run the web server
  become: yes
  shell:
    cmd: |
      cd /home/ubuntu/backend
      pwd
      # pm2 stop backend
      printenv
      # pm2 delete all
      # pm2 start -f /home/ubuntu/backend/dist/main.js
      npm install
      pm2 stop default 
      pm2 start npm -- start
      pm2 status
  register: print_result

- name: "Export run webserver"
  debug:
    msg: "{{ print_result.stdout_lines }}"

# - name: "Register Export curl 3030"
#   become: yes
#   shell: "printenv"
#   register: helloNodeDebug3

# - name: "Export curl 3030"
#   debug:
#     msg: "{{ helloNodeDebug3.stdout_lines }}"