---
- name: Create directory
  become: yes
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Copy compressed backend folder 
  become: yes
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend
    owner: ubuntu

- name: Run the web server
  become: yes
  shell:
    cmd: |
      # cd /home/ubuntu/backend
      # pm2 stop backend
      pm2 delete all
      pm2 start -f /home/ubuntu/backend/dist/main.js