---
- name: Create directory
  become: yes
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Copy compressed backend folder 
  become: yes
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend
    owner: ubuntu

- name: Run the web server
  become: yes
  shell:
    cmd: |
      # cd /home/ubuntu/backend
      # pm2 stop backend
      pwd
      printenv
      pm2 delete all
      pm2 start -f /home/ubuntu/backend/dist/main.js


- name: "print to stdout Evironemnt from ec2 "
  become: yes
  shell: "pm2 log"
  register: helloNodeDebug

- name: "install node toantc3 helloNodeDebug debug"
  debug:
    msg: "{{ helloNodeDebug.stdout_lines }}"

- name: "Register Export curl 3030"
  become: yes
  shell: "curl localhost:3030/api/status"
  register: helloNodeDebug3

- name: "Export curl 3030"
  debug:
    msg: "{{ helloNodeDebug3.stdout_lines }}"